import { useState } from 'react';
import { useSupabaseAuth } from '@/hooks/useSupabaseAuth';
import { useProfile } from '@/hooks/useProfile';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Loader2, TrendingUp, Search } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

interface Hashtag {
  id: string;
  hashtag: string;
  usage_count: number;
  total_engagement: number;
  avg_engagement: number;
  first_used: string;
  last_used: string;
}

export default function Hashtags() {
  const { user } = useSupabaseAuth();
  const { data: profile } = useProfile(user?.id);
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState<'engagement' | 'usage' | 'avg'>('engagement');

  const { data: hashtags, isLoading } = useQuery({
    queryKey: ['hashtags', profile?.id],
    queryFn: async () => {
      if (!profile?.id) return [];

      const { data, error } = await supabase
        .from('hashtags_metrics')
        .select('*')
        .eq('profile_id', profile.id)
        .order('total_engagement', { ascending: false });

      if (error) throw error;
      return (data || []) as Hashtag[];
    },
    enabled: !!profile?.id,
  });

  const filteredHashtags = hashtags?.filter((h) =>
    h.hashtag.toLowerCase().includes(searchTerm.toLowerCase())
  ) || [];

  const sortedHashtags = [...filteredHashtags].sort((a, b) => {
    switch (sortBy) {
      case 'engagement':
        return b.total_engagement - a.total_engagement;
      case 'usage':
        return b.usage_count - a.usage_count;
      case 'avg':
        return b.avg_engagement - a.avg_engagement;
      default:
        return 0;
    }
  });

  const topHashtags = sortedHashtags.slice(0, 10);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold">Hashtag Performance</h1>
        <p className="text-gray-600 mt-2">Analyze your hashtag strategy and discover top performers</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 mb-1">Total Hashtags Used</p>
                <p className="text-3xl font-bold">{hashtags?.length || 0}</p>
              </div>
              <TrendingUp className="w-8 h-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 mb-1">Avg Engagement per Hashtag</p>
                <p className="text-3xl font-bold">
                  {hashtags && hashtags.length > 0
                    ? (hashtags.reduce((sum, h) => sum + h.avg_engagement, 0) / hashtags.length).toFixed(0)
                    : '0'}
                </p>
              </div>
              <TrendingUp className="w-8 h-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 mb-1">Top Hashtag Engagement</p>
                <p className="text-3xl font-bold">
                  {topHashtags[0]?.total_engagement.toLocaleString() || '0'}
                </p>
              </div>
              <TrendingUp className="w-8 h-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Top Hashtags Chart */}
      {topHashtags.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Top 10 Hashtags by Engagement</CardTitle>
            <CardDescription>Total engagement generated by each hashtag</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={topHashtags}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="hashtag" angle={-45} textAnchor="end" height={100} />
                <YAxis />
                <Tooltip />
                <Bar dataKey="total_engagement" fill="#ec4899" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}

      {/* Hashtags List */}
      <Card>
        <CardHeader>
          <CardTitle>All Hashtags</CardTitle>
          <CardDescription>Complete list of hashtags with performance metrics</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {/* Search and Sort */}
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-3 w-4 h-4 text-gray-400" />
                <Input
                  placeholder="Search hashtags..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as any)}
                className="px-4 py-2 border border-gray-300 rounded-lg"
              >
                <option value="engagement">Sort by Engagement</option>
                <option value="usage">Sort by Usage</option>
                <option value="avg">Sort by Avg Engagement</option>
              </select>
            </div>

            {/* Hashtags Table */}
            {sortedHashtags.length === 0 ? (
              <p className="text-center text-gray-600 py-8">No hashtags found</p>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left py-3 px-4 font-semibold">Hashtag</th>
                      <th className="text-right py-3 px-4 font-semibold">Usage</th>
                      <th className="text-right py-3 px-4 font-semibold">Total Engagement</th>
                      <th className="text-right py-3 px-4 font-semibold">Avg Engagement</th>
                      <th className="text-left py-3 px-4 font-semibold">Last Used</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sortedHashtags.map((hashtag) => (
                      <tr key={hashtag.id} className="border-b hover:bg-gray-50">
                        <td className="py-3 px-4">
                          <a
                            href={`https://instagram.com/explore/tags/${hashtag.hashtag.replace('#', '')}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-blue-600 hover:underline font-medium"
                          >
                            {hashtag.hashtag}
                          </a>
                        </td>
                        <td className="text-right py-3 px-4">{hashtag.usage_count}</td>
                        <td className="text-right py-3 px-4 font-semibold">
                          {hashtag.total_engagement.toLocaleString()}
                        </td>
                        <td className="text-right py-3 px-4">{hashtag.avg_engagement.toFixed(0)}</td>
                        <td className="py-3 px-4 text-sm text-gray-600">
                          {new Date(hashtag.last_used).toLocaleDateString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
